/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as AssessmentsIdRouteImport } from './routes/assessments/$id'
import { Route as OpportunitiesNewRouteImport } from './routes/opportunities/new'
import { Route as PoliciesIndexRouteImport } from './routes/policies/index'
import { Route as PoliciesIdRouteImport } from './routes/policies/$id'
import { Route as PoliciesNewRouteImport } from './routes/policies/new'
import { Route as ApiV1ActivityRouteImport } from './routes/api/v1/activity'
import { Route as ApiV1ConfigRouteImport } from './routes/api/v1/config'
import { Route as ApiV1SourcesRouteImport } from './routes/api/v1/sources'
import { Route as OpportunitiesIdIndexRouteImport } from './routes/opportunities/$id/index'
import { Route as OpportunitiesIdDriftRouteImport } from './routes/opportunities/$id/drift'
import { Route as ApiV1AssessmentsIdRouteImport } from './routes/api/v1/assessments/$id'
import { Route as ApiV1HealthLiveRouteImport } from './routes/api/v1/health/live'
import { Route as ApiV1HealthReadyRouteImport } from './routes/api/v1/health/ready'
import { Route as ApiV1OpportunitiesIndexRouteImport } from './routes/api/v1/opportunities/index'
import { Route as ApiV1PoliciesIndexRouteImport } from './routes/api/v1/policies/index'
import { Route as ApiV1PoliciesIdRouteImport } from './routes/api/v1/policies/$id'
import { Route as ApiV1OpportunitiesIdIndexRouteImport } from './routes/api/v1/opportunities/$id/index'
import { Route as ApiV1OpportunitiesIdAssessmentsRouteImport } from './routes/api/v1/opportunities/$id/assessments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIdRoute = AssessmentsIdRouteImport.update({
  id: '/assessments/$id',
  path: '/assessments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesNewRoute = OpportunitiesNewRouteImport.update({
  id: '/opportunities/new',
  path: '/opportunities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIndexRoute = PoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIdRoute = PoliciesIdRouteImport.update({
  id: '/policies/$id',
  path: '/policies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesNewRoute = PoliciesNewRouteImport.update({
  id: '/policies/new',
  path: '/policies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ActivityRoute = ApiV1ActivityRouteImport.update({
  id: '/api/v1/activity',
  path: '/api/v1/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ConfigRoute = ApiV1ConfigRouteImport.update({
  id: '/api/v1/config',
  path: '/api/v1/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SourcesRoute = ApiV1SourcesRouteImport.update({
  id: '/api/v1/sources',
  path: '/api/v1/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdIndexRoute = OpportunitiesIdIndexRouteImport.update({
  id: '/opportunities/$id/',
  path: '/opportunities/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdDriftRoute = OpportunitiesIdDriftRouteImport.update({
  id: '/opportunities/$id/drift',
  path: '/opportunities/$id/drift',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AssessmentsIdRoute = ApiV1AssessmentsIdRouteImport.update({
  id: '/api/v1/assessments/$id',
  path: '/api/v1/assessments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthLiveRoute = ApiV1HealthLiveRouteImport.update({
  id: '/api/v1/health/live',
  path: '/api/v1/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthReadyRoute = ApiV1HealthReadyRouteImport.update({
  id: '/api/v1/health/ready',
  path: '/api/v1/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpportunitiesIndexRoute = ApiV1OpportunitiesIndexRouteImport.update({
  id: '/api/v1/opportunities/',
  path: '/api/v1/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PoliciesIndexRoute = ApiV1PoliciesIndexRouteImport.update({
  id: '/api/v1/policies/',
  path: '/api/v1/policies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PoliciesIdRoute = ApiV1PoliciesIdRouteImport.update({
  id: '/api/v1/policies/$id',
  path: '/api/v1/policies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpportunitiesIdIndexRoute =
  ApiV1OpportunitiesIdIndexRouteImport.update({
    id: '/api/v1/opportunities/$id/',
    path: '/api/v1/opportunities/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1OpportunitiesIdAssessmentsRoute =
  ApiV1OpportunitiesIdAssessmentsRouteImport.update({
    id: '/api/v1/opportunities/$id/assessments',
    path: '/api/v1/opportunities/$id/assessments',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/docs': typeof DocsRoute
  '/explore': typeof ExploreRoute
  '/methodology': typeof MethodologyRoute
  '/roadmap': typeof RoadmapRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/policies/$id': typeof PoliciesIdRoute
  '/policies/new': typeof PoliciesNewRoute
  '/policies/': typeof PoliciesIndexRoute
  '/api/v1/activity': typeof ApiV1ActivityRoute
  '/api/v1/config': typeof ApiV1ConfigRoute
  '/api/v1/sources': typeof ApiV1SourcesRoute
  '/opportunities/$id/drift': typeof OpportunitiesIdDriftRoute
  '/opportunities/$id/': typeof OpportunitiesIdIndexRoute
  '/api/v1/assessments/$id': typeof ApiV1AssessmentsIdRoute
  '/api/v1/health/live': typeof ApiV1HealthLiveRoute
  '/api/v1/health/ready': typeof ApiV1HealthReadyRoute
  '/api/v1/policies/$id': typeof ApiV1PoliciesIdRoute
  '/api/v1/opportunities/': typeof ApiV1OpportunitiesIndexRoute
  '/api/v1/policies/': typeof ApiV1PoliciesIndexRoute
  '/api/v1/opportunities/$id/assessments': typeof ApiV1OpportunitiesIdAssessmentsRoute
  '/api/v1/opportunities/$id/': typeof ApiV1OpportunitiesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/docs': typeof DocsRoute
  '/explore': typeof ExploreRoute
  '/methodology': typeof MethodologyRoute
  '/roadmap': typeof RoadmapRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/policies/$id': typeof PoliciesIdRoute
  '/policies/new': typeof PoliciesNewRoute
  '/policies': typeof PoliciesIndexRoute
  '/api/v1/activity': typeof ApiV1ActivityRoute
  '/api/v1/config': typeof ApiV1ConfigRoute
  '/api/v1/sources': typeof ApiV1SourcesRoute
  '/opportunities/$id/drift': typeof OpportunitiesIdDriftRoute
  '/opportunities/$id': typeof OpportunitiesIdIndexRoute
  '/api/v1/assessments/$id': typeof ApiV1AssessmentsIdRoute
  '/api/v1/health/live': typeof ApiV1HealthLiveRoute
  '/api/v1/health/ready': typeof ApiV1HealthReadyRoute
  '/api/v1/policies/$id': typeof ApiV1PoliciesIdRoute
  '/api/v1/opportunities': typeof ApiV1OpportunitiesIndexRoute
  '/api/v1/policies': typeof ApiV1PoliciesIndexRoute
  '/api/v1/opportunities/$id/assessments': typeof ApiV1OpportunitiesIdAssessmentsRoute
  '/api/v1/opportunities/$id': typeof ApiV1OpportunitiesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/docs': typeof DocsRoute
  '/explore': typeof ExploreRoute
  '/methodology': typeof MethodologyRoute
  '/roadmap': typeof RoadmapRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/policies/$id': typeof PoliciesIdRoute
  '/policies/new': typeof PoliciesNewRoute
  '/policies/': typeof PoliciesIndexRoute
  '/api/v1/activity': typeof ApiV1ActivityRoute
  '/api/v1/config': typeof ApiV1ConfigRoute
  '/api/v1/sources': typeof ApiV1SourcesRoute
  '/opportunities/$id/drift': typeof OpportunitiesIdDriftRoute
  '/opportunities/$id/': typeof OpportunitiesIdIndexRoute
  '/api/v1/assessments/$id': typeof ApiV1AssessmentsIdRoute
  '/api/v1/health/live': typeof ApiV1HealthLiveRoute
  '/api/v1/health/ready': typeof ApiV1HealthReadyRoute
  '/api/v1/policies/$id': typeof ApiV1PoliciesIdRoute
  '/api/v1/opportunities/': typeof ApiV1OpportunitiesIndexRoute
  '/api/v1/policies/': typeof ApiV1PoliciesIndexRoute
  '/api/v1/opportunities/$id/assessments': typeof ApiV1OpportunitiesIdAssessmentsRoute
  '/api/v1/opportunities/$id/': typeof ApiV1OpportunitiesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/docs'
    | '/explore'
    | '/methodology'
    | '/roadmap'
    | '/assessments/$id'
    | '/opportunities/new'
    | '/policies/$id'
    | '/policies/new'
    | '/policies/'
    | '/api/v1/activity'
    | '/api/v1/config'
    | '/api/v1/sources'
    | '/opportunities/$id/drift'
    | '/opportunities/$id/'
    | '/api/v1/assessments/$id'
    | '/api/v1/health/live'
    | '/api/v1/health/ready'
    | '/api/v1/policies/$id'
    | '/api/v1/opportunities/'
    | '/api/v1/policies/'
    | '/api/v1/opportunities/$id/assessments'
    | '/api/v1/opportunities/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/docs'
    | '/explore'
    | '/methodology'
    | '/roadmap'
    | '/assessments/$id'
    | '/opportunities/new'
    | '/policies/$id'
    | '/policies/new'
    | '/policies'
    | '/api/v1/activity'
    | '/api/v1/config'
    | '/api/v1/sources'
    | '/opportunities/$id/drift'
    | '/opportunities/$id'
    | '/api/v1/assessments/$id'
    | '/api/v1/health/live'
    | '/api/v1/health/ready'
    | '/api/v1/policies/$id'
    | '/api/v1/opportunities'
    | '/api/v1/policies'
    | '/api/v1/opportunities/$id/assessments'
    | '/api/v1/opportunities/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/docs'
    | '/explore'
    | '/methodology'
    | '/roadmap'
    | '/assessments/$id'
    | '/opportunities/new'
    | '/policies/$id'
    | '/policies/new'
    | '/policies/'
    | '/api/v1/activity'
    | '/api/v1/config'
    | '/api/v1/sources'
    | '/opportunities/$id/drift'
    | '/opportunities/$id/'
    | '/api/v1/assessments/$id'
    | '/api/v1/health/live'
    | '/api/v1/health/ready'
    | '/api/v1/policies/$id'
    | '/api/v1/opportunities/'
    | '/api/v1/policies/'
    | '/api/v1/opportunities/$id/assessments'
    | '/api/v1/opportunities/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DocsRoute: typeof DocsRoute
  ExploreRoute: typeof ExploreRoute
  MethodologyRoute: typeof MethodologyRoute
  RoadmapRoute: typeof RoadmapRoute
  AssessmentsIdRoute: typeof AssessmentsIdRoute
  OpportunitiesNewRoute: typeof OpportunitiesNewRoute
  PoliciesIdRoute: typeof PoliciesIdRoute
  PoliciesNewRoute: typeof PoliciesNewRoute
  PoliciesIndexRoute: typeof PoliciesIndexRoute
  ApiV1ActivityRoute: typeof ApiV1ActivityRoute
  ApiV1ConfigRoute: typeof ApiV1ConfigRoute
  ApiV1SourcesRoute: typeof ApiV1SourcesRoute
  OpportunitiesIdDriftRoute: typeof OpportunitiesIdDriftRoute
  OpportunitiesIdIndexRoute: typeof OpportunitiesIdIndexRoute
  ApiV1AssessmentsIdRoute: typeof ApiV1AssessmentsIdRoute
  ApiV1HealthLiveRoute: typeof ApiV1HealthLiveRoute
  ApiV1HealthReadyRoute: typeof ApiV1HealthReadyRoute
  ApiV1PoliciesIdRoute: typeof ApiV1PoliciesIdRoute
  ApiV1OpportunitiesIndexRoute: typeof ApiV1OpportunitiesIndexRoute
  ApiV1PoliciesIndexRoute: typeof ApiV1PoliciesIndexRoute
  ApiV1OpportunitiesIdAssessmentsRoute: typeof ApiV1OpportunitiesIdAssessmentsRoute
  ApiV1OpportunitiesIdIndexRoute: typeof ApiV1OpportunitiesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$id': {
      id: '/assessments/$id'
      path: '/assessments/$id'
      fullPath: '/assessments/$id'
      preLoaderRoute: typeof AssessmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/new': {
      id: '/opportunities/new'
      path: '/opportunities/new'
      fullPath: '/opportunities/new'
      preLoaderRoute: typeof OpportunitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/': {
      id: '/policies/'
      path: '/policies'
      fullPath: '/policies/'
      preLoaderRoute: typeof PoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$id': {
      id: '/policies/$id'
      path: '/policies/$id'
      fullPath: '/policies/$id'
      preLoaderRoute: typeof PoliciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/new': {
      id: '/policies/new'
      path: '/policies/new'
      fullPath: '/policies/new'
      preLoaderRoute: typeof PoliciesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/activity': {
      id: '/api/v1/activity'
      path: '/api/v1/activity'
      fullPath: '/api/v1/activity'
      preLoaderRoute: typeof ApiV1ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/config': {
      id: '/api/v1/config'
      path: '/api/v1/config'
      fullPath: '/api/v1/config'
      preLoaderRoute: typeof ApiV1ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sources': {
      id: '/api/v1/sources'
      path: '/api/v1/sources'
      fullPath: '/api/v1/sources'
      preLoaderRoute: typeof ApiV1SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id/': {
      id: '/opportunities/$id/'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id/'
      preLoaderRoute: typeof OpportunitiesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id/drift': {
      id: '/opportunities/$id/drift'
      path: '/opportunities/$id/drift'
      fullPath: '/opportunities/$id/drift'
      preLoaderRoute: typeof OpportunitiesIdDriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/assessments/$id': {
      id: '/api/v1/assessments/$id'
      path: '/api/v1/assessments/$id'
      fullPath: '/api/v1/assessments/$id'
      preLoaderRoute: typeof ApiV1AssessmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health/live': {
      id: '/api/v1/health/live'
      path: '/api/v1/health/live'
      fullPath: '/api/v1/health/live'
      preLoaderRoute: typeof ApiV1HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health/ready': {
      id: '/api/v1/health/ready'
      path: '/api/v1/health/ready'
      fullPath: '/api/v1/health/ready'
      preLoaderRoute: typeof ApiV1HealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/opportunities/': {
      id: '/api/v1/opportunities/'
      path: '/api/v1/opportunities'
      fullPath: '/api/v1/opportunities/'
      preLoaderRoute: typeof ApiV1OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/policies/': {
      id: '/api/v1/policies/'
      path: '/api/v1/policies'
      fullPath: '/api/v1/policies/'
      preLoaderRoute: typeof ApiV1PoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/policies/$id': {
      id: '/api/v1/policies/$id'
      path: '/api/v1/policies/$id'
      fullPath: '/api/v1/policies/$id'
      preLoaderRoute: typeof ApiV1PoliciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/opportunities/$id/': {
      id: '/api/v1/opportunities/$id/'
      path: '/api/v1/opportunities/$id'
      fullPath: '/api/v1/opportunities/$id/'
      preLoaderRoute: typeof ApiV1OpportunitiesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/opportunities/$id/assessments': {
      id: '/api/v1/opportunities/$id/assessments'
      path: '/api/v1/opportunities/$id/assessments'
      fullPath: '/api/v1/opportunities/$id/assessments'
      preLoaderRoute: typeof ApiV1OpportunitiesIdAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DocsRoute: DocsRoute,
  ExploreRoute: ExploreRoute,
  MethodologyRoute: MethodologyRoute,
  RoadmapRoute: RoadmapRoute,
  AssessmentsIdRoute: AssessmentsIdRoute,
  OpportunitiesNewRoute: OpportunitiesNewRoute,
  PoliciesIdRoute: PoliciesIdRoute,
  PoliciesNewRoute: PoliciesNewRoute,
  PoliciesIndexRoute: PoliciesIndexRoute,
  ApiV1ActivityRoute: ApiV1ActivityRoute,
  ApiV1ConfigRoute: ApiV1ConfigRoute,
  ApiV1SourcesRoute: ApiV1SourcesRoute,
  OpportunitiesIdDriftRoute: OpportunitiesIdDriftRoute,
  OpportunitiesIdIndexRoute: OpportunitiesIdIndexRoute,
  ApiV1AssessmentsIdRoute: ApiV1AssessmentsIdRoute,
  ApiV1HealthLiveRoute: ApiV1HealthLiveRoute,
  ApiV1HealthReadyRoute: ApiV1HealthReadyRoute,
  ApiV1PoliciesIdRoute: ApiV1PoliciesIdRoute,
  ApiV1OpportunitiesIndexRoute: ApiV1OpportunitiesIndexRoute,
  ApiV1PoliciesIndexRoute: ApiV1PoliciesIndexRoute,
  ApiV1OpportunitiesIdAssessmentsRoute: ApiV1OpportunitiesIdAssessmentsRoute,
  ApiV1OpportunitiesIdIndexRoute: ApiV1OpportunitiesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
